swagger: "2.0"
info:
  description: "TEDU social API docs"
  version: "1.0.0"
  title: "TEDU social"
  termOfService: "http://tedu.com.vn"
  contact:
    email: "tedu.international@gmail.com"
  license:
    name: "MIT"
    url: "https://opensource.org/license/mit/"
host: "localhost:5000"
basePath: "/api/v1"
tags: 
- name: "auth"
  description: "Authentication APIs"
- name: "Conversations"
  description: "Message APIs"
- name: "Groups"
  description: "Group APIs"
- name: "Posts"
  description: "Post APIs"
- name: "Profiles"
  description: "Profile APIs"
- name: "Users"
  description: "User APIs"
schemas:
- "http"
paths:
  /auth:
    post:
      tags:
      - "auth"
      summary: "Login API and get token"
      description: "Input conversationId and to and text"
      operationId: "login"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Send message to user"
        required: true
        schema: 
          $ref: "#/definitions/LoginDto"
      responses:
        "400":
          description: "Invalid input"
  /conversations:
    post:
      tags:
      - "Conversations"
      summary: "Send message"
      description: "Input email and password"
      operationId: "login"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Send message"
        required: true
        schema: 
          $ref: "#/definitions/SendMessageDto"
      responses:
        "400":
          description: "Invalid input"
definitions:
    LoginDto:
      type: "object"
      properties:
        email:
          type: "string"
        password:
          type: "string"
    SendMessageDto:
      type: "object"
      properties:
        conversationId:
          type: "string"
        to:
          type: "string"
        text:
          type: "string"
          
